### ISSUE TITLE
Tussenmomentje

### ISSUE THREAD

**Issue by Mennauu** [MohamadAlGhorani/browser-technologies-1920#2]
_**Graag wil ik feedback op mijn inputs in de bestand stapTwee.ejs ik wil weten of deze inputs genoeg zijn.**_

Niet veel op aan te merken, het ziet er goed uit. Haal alleen wel die `<p>'s` weg die om je `<textarea>'s` staan. Het is genoeg!

_**ik wil graag feedback op mijn ux en de semantisch html**_

Ook als aanvulling op de eerste vraag, je kan een `<legend>` toevoegen aan je `<fieldset>` tags. Lees vooral deze documentatie door: https://www.w3.org/WAI/tutorials/forms/. Daar staat goed uitgelegd hoe je het semantisch in orde kan maken, evenals accesibility.

Ik kan voor nu alleen de functionaal laag zien, en dat ziet er prima uit. Vergeet niet om een 'state' te maken voor de gebruikers als zij op `opslaan` klikken. Het is nu nog niet duidelijk dat ze de URL moeten opslaan om verder te kunnen gaan.

_**ik wil graag feedback op het readme en wat ik er in moet schrijven.**_

Ik kan je niet precies vertellen wat er allemaal in de readme moet. Iedereen doet het verschillend en op z'n eigen manier. Ik kan je adviseren om naar [mijn readme](https://github.com/Mennauu/browser-technologies-1819) van vorig jaar te kijken, evenals kan je inspiratie op doen door naar de readme's van de andere studenten te kijken:

https://github.com/MohamadAlGhorani/browser-technologies-1920/network/members

**Comment by MohamadAlGhorani** [comment]
Dankjewl voor je feedback ik heb inderdaad alleen de functioneel lagje gemaakt. bij het opslaan van de formulier je kunt de hele website verlaten en als je weer inlogt kan je verder met je formulier dus het heeft niks te maken met de url nu. :D ik heb inlog op basis van student nummer.
